### ISSUE TITLE
Radarr does not save Quality Profiles

### ISSUE THREAD

**Issue by donjuanmon** [lokenx/plexrequests-meteor#449]
It seems like radarr is not saving my quality profiles after selecting one... this causes approvals to fail. This function works normally in sonarr. 

To clarify, I can pull the quality profiles from my radarr instance, but when I navigate from admin settings, they disappear. I have made sure to hit the "save" button before navigating away.

I hope this is easy to fix!

**Comment by GielDeBleser** [comment]
i'm having same issue for Radarr and also Sonarr. I'm running the latest version.
The errors I get on trying to approve a series or movie are:

`Radarr Movie Post -> Match error: Expected string, got undefined`
`Sonarr Series Post -> Match error: Expected number, got undefined`

as the "quality profiles"-setting seems to reset empty after a page reload or switching tabs

**Comment by desimaniac** [comment]
I believe it remembers the profile but just doesn't show it as saved.

**Comment by rigrassm** [comment]
Yeah, It is being saved its just the UI that's not wanting to show it after
it's been saved. Going to try and work on this and a few other items in the
next couple days.

**Comment by Kuroyukihimeeee** [comment]
Also seeing same error here
`Radarr Movie Post -> Match error: Expected string, got undefined`
`Sonarr Series Post -> Match error: Expected number, got undefined`

Radarr Ver. 0.2.0.453
Sonarr Ver. 2.0.0.4645
Request Ver. 1.20.2 master

**Comment by tiddles155** [comment]
has this been resolved? having same issue

**Comment by rigrassm** [comment]
It has not been resolved yet, it's been a lower priority issue since the
value you save is stored correctly. Until I or someone else get a chance to
look into it you just need to hit the get profiles button to have them
repopulate.

**Comment by tiddles155** [comment]
radarr throws out
Radarr Movie Post -> Match error: Expected string, got undefined

sonarr throws out
Sonarr Series Post -> failed [400] [
I20170707-20:08:42.582(8)?    {
I20170707-20:08:42.583(8)?      "propertyName": "RootFolderPath",
I20170707-20:08:42.583(8)?      "errorMessage": "Invalid Path",
I20170707-20:08:42.583(8)?      "attemptedValue": "F:/TV Shows",
I20170707-20:08:42.593(8)?      "formattedMessageArguments": [],
I20170707-20:08:42.593(8)?      "formattedMessagePlaceholderValues": {
I20170707-20:08:42.593(8)?        "propertyName": "Root Folder Path",
I20170707-20:08:42.593(8)?        "propertyValue": "F:/TV Shows"

**Comment by tiddles155** [comment]
yer i hit the get profiles button but it still wont allow me to approve requests

**Comment by rigrassm** [comment]
What version of PR are you running?

**Comment by tiddles155** [comment]
it shows blank but i did a clean install from git

**Comment by rigrassm** [comment]
Hmm, when you set the profile, are you clicking the update settings button
after? We fixed the approval issue a while back so that shouldn't be
happening.

**Comment by tiddles155** [comment]
Uer after i hit show profiles i select the profile and hit the update settings button, to be honest i was a few veraions behind and was having issues with radar so i updated to the latest now cant apprkve from sonarr or radarr, strange...

**Comment by rigrassm** [comment]
Try doing a fresh install, move the old PlexRequests folder, git clone the
repo, start Plexrequests and set up Radarr, do a test request and approval.

If that works you can stop Plexrequests and then copy the database over
from the old folder to the new one and then restart Plexrequests. That'll
bring in all your old data.

**Comment by sudo-kraken** [comment]
I have done a fresh install today from dockerhub, this is still happening do you have a fix for it not remembering the profile after you update the settings?

**Comment by sudo-kraken** [comment]
It is also doing this for sonarr, so I cant use plex requests at all

**Comment by RickyGrassmuck** [comment]
@Joeharrison94 this project has been unmaintained now for quite some time and I don't have any plans to start back up in the foreseeable future. I can't speak for the creator but I don't think they will be coming back either.

Your best bet would be to switch over to a project like Ombi which is being actively developed.
